### ISSUE TITLE
Aop Vote menu not appearing. 

### ISSUE THREAD

**Issue by LibertyCitys** [zapprr/republic-core#2]
When using /AopVote your text entry is limited to one line (so not much of a vote) I assume there is meant to be a menu but it does not appear. 0 Errors appear in the Console.

**Comment by zapprr** [comment]
AOP votes should work via /aopvote [AOP 1]/[AOP 2]/[AOP 3]. So an example would be

`/aopvote Sandy Shores/Paleto Bay/Vespucci`

You'll also need to make sure that players doing the AOP vote command have permission to use the /aopvote command. Once a vote's commenced, an AOP vote menu will appear for all player.
